package takagi.ru.monica.steam.store.freebie.data

import java.time.Instant
import java.time.LocalDateTime
import java.time.Month
import java.time.ZoneId
import java.time.format.DateTimeFormatterBuilder
import java.util.Locale
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.contentOrNull
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import org.jsoup.Jsoup
import org.jsoup.nodes.Element
import takagi.ru.monica.steam.store.freebie.domain.SteamFreebieClaimMethod
import takagi.ru.monica.steam.store.freebie.domain.SteamFreebieItem
import takagi.ru.monica.steam.store.freebie.domain.SteamFreebieOfferKind
import takagi.ru.monica.steam.store.freebie.domain.SteamFreebieProductType

internal data class SteamFreebieCandidate(
    val appId: Int,
    val name: String,
    val imageUrl: String,
    val storeUrl: String,
    val originalPriceText: String,
    val finalPriceText: String,
    val discountPercent: Int
)

/** The hidden form Steam renders for a permanent free-license promotion. */
internal data class SteamFreebieClaimForm(
    val sessionId: String,
    val snr: String,
    val originatingSnr: String,
    val action: String,
    val packageId: Int?
)

internal object SteamFreebieSearchParser {
    private val json = Json { ignoreUnknownKeys = true }

    fun parse(payload: String): List<SteamFreebieCandidate> {
        val html = runCatching {
            json.parseToJsonElement(payload)
                .jsonObject["results_html"]
                ?.jsonPrimitive
                ?.contentOrNull
                .orEmpty()
        }.getOrDefault("")
        if (html.isBlank()) return emptyList()
        val document = Jsoup.parseBodyFragment(html, STEAM_STORE_BASE)
        return document.select("a.search_result_row[data-ds-appid]")
            .mapNotNull(::candidate)
            .distinctBy(SteamFreebieCandidate::appId)
    }

    private fun candidate(row: Element): SteamFreebieCandidate? {
        val appId = row.attr("data-ds-appid").toIntOrNull()?.takeIf { it > 0 }
            ?: return null
        val price = row.selectFirst(".search_price_discount_combined")
            ?: row.selectFirst(".discount_block")
            ?: return null
        val finalPriceMinor = price.attr("data-price-final").toIntOrNull()
            ?: row.selectFirst("[data-price-final]")?.attr("data-price-final")?.toIntOrNull()
        val discountBlock = row.selectFirst(".discount_block")
        val discountPercent = discountBlock?.attr("data-discount")?.toIntOrNull()
            ?: discountBlock?.selectFirst(".discount_pct")?.text()
                ?.filter(Char::isDigit)
                ?.toIntOrNull()
            ?: 0
        val combinedText = row.text()
        val temporaryFree = TEMPORARY_FREE_TEXT.containsMatchIn(combinedText)
        if (finalPriceMinor != 0 || (discountPercent < 100 && !temporaryFree)) return null
        val name = row.selectFirst(".title")?.text()?.trim().orEmpty()
        if (name.isBlank()) return null
        return SteamFreebieCandidate(
            appId = appId,
            name = name,
            imageUrl = row.selectFirst(".search_capsule img[src]")?.absUrl("src").orEmpty(),
            storeUrl = row.absUrl("href").substringBefore('?').ifBlank {
                "$STEAM_STORE_BASE/app/$appId/"
            },
            originalPriceText = row.selectFirst(".discount_original_price")?.text().orEmpty(),
            finalPriceText = row.selectFirst(".discount_final_price")?.text().orEmpty(),
            discountPercent = discountPercent
        )
    }

    private val TEMPORARY_FREE_TEXT = Regex(
        "free\\s+weekend|play\\s+for\\s+free|免费周末|免费畅玩",
        RegexOption.IGNORE_CASE
    )
    private const val STEAM_STORE_BASE = "https://store.steampowered.com"
}

internal object SteamFreebieOfferPageParser {
    /** Extract the CSRF/session token generated by Steam for this store page. */
    fun parseSessionId(html: String): String? = parseClaimForm(html)?.sessionId
        ?: SESSION_ID_SCRIPT.find(html)?.groupValues?.getOrNull(1)
            ?.trim()
            ?.takeIf { it.matches(SESSION_ID_PATTERN) }

    /** Preserve every hidden value used by Steam's own add-to-account form. */
    fun parseClaimForm(html: String): SteamFreebieClaimForm? {
        val document = Jsoup.parse(html)
        val form = document.selectFirst("form[action*=/freelicense/addfreelicense/]")
            ?: return null
        val sessionId = form.selectFirst("input[name=sessionid]")
            ?.attr("value")
            ?.trim()
            ?.takeIf { it.matches(SESSION_ID_PATTERN) }
            ?: return null
        return SteamFreebieClaimForm(
            sessionId = sessionId,
            snr = form.selectFirst("input[name=snr]")?.attr("value").orEmpty(),
            originatingSnr = form.selectFirst("input[name=originating_snr]")
                ?.attr("value")
                .orEmpty(),
            action = form.selectFirst("input[name=action]")?.attr("value")
                ?.ifBlank { "add_to_cart" }
                ?: "add_to_cart",
            packageId = form.selectFirst("input[name=subid]")
                ?.attr("value")
                ?.toIntOrNull()
                ?.takeIf { it > 0 }
        )
    }

    fun parse(
        candidate: SteamFreebieCandidate,
        html: String,
        nowMillis: Long = System.currentTimeMillis(),
        zoneId: ZoneId = ZoneId.systemDefault()
    ): SteamFreebieItem {
        val document = Jsoup.parse(html, candidate.storeUrl)
        val freeLicenseForm = document.selectFirst(
            "form[action*=/freelicense/addfreelicense/]"
        )
        val freeLicensePackageId = freeLicenseForm
            ?.selectFirst("input[name=subid]")
            ?.attr("value")
            ?.toIntOrNull()
            ?.takeIf { it > 0 }
        val zeroPriceCartForm = document.select(
            ".game_area_purchase_game:has([data-price-final=0]) form[action*=/cart/]"
        ).firstOrNull()
        val checkoutPackageId = zeroPriceCartForm
            ?.selectFirst("input[name=subid]")
            ?.attr("value")
            ?.toIntOrNull()
            ?.takeIf { it > 0 }
        val offerContainer = freeLicenseForm?.closest(".game_area_purchase_game")
            ?: zeroPriceCartForm?.closest(".game_area_purchase_game")
            ?: document.selectFirst(".game_area_purchase_game")
        val offerText = offerContainer?.selectFirst(
            ".game_purchase_discount_quantity, .game_purchase_discount_countdown"
        )?.text().orEmpty()
        val temporaryOffer = TEMPORARY_FREE_TEXT.containsMatchIn(offerText)
        val keepsForever = freeLicensePackageId != null ||
            checkoutPackageId != null ||
            KEEP_FOREVER_TEXT.containsMatchIn(offerText) ||
            (candidate.discountPercent >= 100 && !temporaryOffer)
        val dlcBubble = document.selectFirst(".game_area_dlc_bubble")
        val baseGameAppId = dlcBubble?.selectFirst("a[href*=/app/]")
            ?.absUrl("href")
            ?.let(::appIdFromUrl)
        val pageImage = document.selectFirst("meta[property=og:image]")
            ?.attr("content")
            .orEmpty()
        val pageType = when {
            dlcBubble != null -> SteamFreebieProductType.DLC
            document.selectFirst("#game_area_purchase") != null -> SteamFreebieProductType.GAME
            else -> SteamFreebieProductType.OTHER
        }
        return SteamFreebieItem(
            appId = candidate.appId,
            packageId = freeLicensePackageId ?: checkoutPackageId,
            name = candidate.name,
            imageUrl = pageImage.ifBlank { candidate.imageUrl },
            storeUrl = candidate.storeUrl,
            offerKind = if (keepsForever) {
                SteamFreebieOfferKind.KEEP_FOREVER
            } else {
                SteamFreebieOfferKind.FREE_WEEKEND
            },
            productType = pageType,
            claimMethod = when {
                freeLicensePackageId != null -> SteamFreebieClaimMethod.FREE_LICENSE
                checkoutPackageId != null -> SteamFreebieClaimMethod.OFFICIAL_CHECKOUT
                else -> SteamFreebieClaimMethod.NONE
            },
            originalPriceText = candidate.originalPriceText,
            finalPriceText = candidate.finalPriceText,
            discountPercent = candidate.discountPercent,
            endsAtEpochMillis = SteamFreebieExpiryParser.parse(
                text = offerText,
                nowMillis = nowMillis,
                zoneId = zoneId
            ),
            baseGameAppId = baseGameAppId
        )
    }

    private fun appIdFromUrl(url: String): Int? = APP_URL.find(url)
        ?.groupValues
        ?.getOrNull(1)
        ?.toIntOrNull()

    private val KEEP_FOREVER_TEXT = Regex(
        "free\\s+to\\s+keep|keep\\s+it\\s+for\\s+free|免费保留|永久入库",
        RegexOption.IGNORE_CASE
    )
    private val TEMPORARY_FREE_TEXT = Regex(
        "free\\s+weekend|play\\s+for\\s+free|free\\s+to\\s+play|免费周末|免费畅玩|限时免费游玩",
        RegexOption.IGNORE_CASE
    )
    private val APP_URL = Regex("/app/(\\d+)", RegexOption.IGNORE_CASE)
    private val SESSION_ID_SCRIPT = Regex(
        "(?i)(?:g_sessionID|sessionID)\\s*[:=]\\s*[\\\"']([^\\\"']+)[\\\"']"
    )
    private val SESSION_ID_PATTERN = Regex("[A-Za-z0-9]{16,64}")
}

internal object SteamFreebieExpiryParser {
    fun parse(
        text: String,
        nowMillis: Long,
        zoneId: ZoneId
    ): Long? {
        if (text.isBlank()) return null
        parseEnglish(text, nowMillis, zoneId)?.let { return it }
        return parseChinese(text, nowMillis, zoneId)
    }

    private fun parseEnglish(text: String, nowMillis: Long, zoneId: ZoneId): Long? {
        val match = ENGLISH_DATE.find(text) ?: return null
        val normalized = match.value
            .replace(Regex("\\s+"), " ")
            .replace(" @ ", "@")
            .replace("@ ", "@")
            .replace(" @", "@")
            .uppercase(Locale.US)
        val parsed = runCatching {
            LocalDateTime.parse(
                "${Instant.ofEpochMilli(nowMillis).atZone(zoneId).year} $normalized",
                DateTimeFormatterBuilder()
                    .parseCaseInsensitive()
                    .appendPattern("yyyy MMM d@h:mma")
                    .toFormatter(Locale.US)
            )
        }.getOrNull() ?: return null
        return futureOccurrence(parsed, nowMillis, zoneId)
    }

    private fun parseChinese(text: String, nowMillis: Long, zoneId: ZoneId): Long? {
        val match = CHINESE_DATE.find(text) ?: return null
        val month = match.groupValues[1].toIntOrNull() ?: return null
        val day = match.groupValues[2].toIntOrNull() ?: return null
        val period = match.groupValues[3]
        val rawHour = match.groupValues[4].toIntOrNull() ?: return null
        val minute = match.groupValues[5].toIntOrNull() ?: return null
        val hour = when {
            period == "下午" && rawHour < 12 -> rawHour + 12
            period == "上午" && rawHour == 12 -> 0
            else -> rawHour
        }
        val now = Instant.ofEpochMilli(nowMillis).atZone(zoneId)
        val parsed = runCatching {
            LocalDateTime.of(now.year, Month.of(month), day, hour, minute)
        }.getOrNull() ?: return null
        return futureOccurrence(parsed, nowMillis, zoneId)
    }

    private fun futureOccurrence(
        value: LocalDateTime,
        nowMillis: Long,
        zoneId: ZoneId
    ): Long {
        var occurrence = value.atZone(zoneId)
        if (occurrence.toInstant().toEpochMilli() < nowMillis) {
            occurrence = occurrence.plusYears(1)
        }
        return occurrence.toInstant().toEpochMilli()
    }

    private val ENGLISH_DATE = Regex(
        "(?i)(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\\s+" +
            "\\d{1,2}\\s*@\\s*\\d{1,2}:\\d{2}\\s*(?:am|pm)"
    )
    private val CHINESE_DATE = Regex(
        "(\\d{1,2})\\s*月\\s*(\\d{1,2})\\s*日\\s*(上午|下午)\\s*" +
            "(\\d{1,2}):(\\d{2})"
    )
}

internal enum class SteamFreebieSubmissionStatus {
    ACCEPTED,
    SESSION_REQUIRED,
    RATE_LIMITED,
    REJECTED
}

internal fun classifySteamFreebieSubmission(
    statusCode: Int,
    location: String?,
    body: String = ""
): SteamFreebieSubmissionStatus = when {
    statusCode == 429 -> SteamFreebieSubmissionStatus.RATE_LIMITED
    location.orEmpty().contains("/login/", ignoreCase = true) ->
        SteamFreebieSubmissionStatus.SESSION_REQUIRED
    LOGIN_RESPONSE_TEXT.containsMatchIn(body) -> SteamFreebieSubmissionStatus.SESSION_REQUIRED
    REJECTED_RESPONSE_TEXT.containsMatchIn(body) -> SteamFreebieSubmissionStatus.REJECTED
    statusCode in 200..399 -> SteamFreebieSubmissionStatus.ACCEPTED
    else -> SteamFreebieSubmissionStatus.REJECTED
}

private val LOGIN_RESPONSE_TEXT = Regex(
    "login_form|sign in to steam|请登录 steam|登录 steam",
    RegexOption.IGNORE_CASE
)
private val REJECTED_RESPONSE_TEXT = Regex(
    "\\\"success\\\"\\s*:\\s*0|error_message|无法添加|" +
        "this item is not available in your region|must own the base game|" +
        "当前地区无法|必须拥有.*本体",
    RegexOption.IGNORE_CASE
)
